# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FbMty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FbMty

pod 'RealmSwift', '~> 2.8.1'
pod 'Alamofire'
pod 'AlamofireObjectMapper'
pod 'STPopup'
pod 'SwiftSpinner'
pod 'IQKeyboardManagerSwift'
pod 'Kingfisher'
pod 'SpaceView'
pod 'Zip', '~> 0.7'
pod 'StatefulTableView', '0.0.17'
pod 'SlidingContainerViewController'
pod 'CTPanoramaView', '~> 1.0'
pod 'PocketSVG', '~> 2.0'
pod 'XLPagerTabStrip', '~> 7.0.0’
pod 'GoogleMaps', '~> 2.0.0’ 
pod 'GooglePlaces', '~> 2.0.0’
pod 'BmoImageLoader'
pod 'SnapKit'
pod 'GrowingTextView'
pod 'FlexiblePageControl'
pod 'ImageSlideshow'
pod 'ImageSlideshow/Kingfisher'

end
